import React from 'react';
import MetaTags from '../components/MetaTags';

const DisclaimerPage: React.FC = () => {
  return (
    <>
      <MetaTags
        title="Disclaimer | Seedream ImagenBrainAi 4.0"
        description="Disclaimer for Seedream ImagenBrainAi 4.0. Understand the terms of use, content ownership, and limitations of our AI-generated content."
        canonicalPath="/disclaimer"
      />
      <div className="max-w-4xl mx-auto prose prose-invert prose-headings:text-green-300 prose-a:text-green-300">
        <h1>Disclaimer</h1>
        <p className="text-sm">Last Updated: {new Date().toLocaleDateString()}</p>
        <p>The information and services provided by Seedream Innovations Inc. through Seedream ImagenBrainAi 4.0 ("Service") are for general informational and creative purposes only. All information on the Service is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or generated content on the Service.</p>

        <h2>1. AI-Generated Content</h2>
        <p>The images and content generated by our AI are the result of complex algorithms and are not created or endorsed by human artists unless explicitly stated. The outputs are generated based on the prompts provided by you, the user.</p>
        <h3>1.1. No Guarantee of Accuracy or Appropriateness</h3>
        <p>The AI may sometimes produce content that is inaccurate, biased, offensive, or otherwise not as intended. We do not guarantee the appropriateness or factual accuracy of any generated content. You are solely responsible for the use of any content you generate.</p>
        <h4>1.2. Potential for Artifacts and Imperfections</h4>
        <p>AI image generation is a new technology and may produce images with unexpected artifacts, inconsistencies, or imperfections. We are continuously working to improve the quality of our models, but we cannot guarantee a flawless output for every prompt.</p>

        <h2>2. No Professional Advice</h2>
        <p>The information provided by the Service is not intended to be a substitute for professional advice. Any content generated, including but not to designs, concepts, or visual representations, should not be considered as professional architectural, engineering, legal, medical, or financial advice. You should consult with a qualified professional for advice tailored to your specific situation.</p>
        
        <h3>2.1. Use in Commercial Projects</h3>
        <p>While you may have rights to use the images you generate (as outlined in our Terms of Service), you are responsible for ensuring that your use of the generated content does not infringe on any third-party rights, such as trademarks or copyrights of existing characters or brands.</p>
        <h4>2.2. No Endorsement</h4>
        <p>Reference to any specific commercial product, process, or service by trade name, trademark, manufacturer, or otherwise, does not constitute or imply its endorsement or recommendation by Seedream Innovations Inc.</p>

        <h2>3. External Links Disclaimer</h2>
        <p>The Service may contain links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the site.</p>
        
        <h2>4. Limitation of Liability</h2>
        <p>Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the service or reliance on any information or content provided on the service. Your use of the service and your reliance on any information on the service is solely at your own risk.</p>
        
        <h5>Generated Content Is Not Human-Made</h5>
        <p>It is important to remember that the outputs of this service are generated by a machine learning model. They are not the creative work of a human artist and should be treated as such.</p>
        <h6>Responsibility of the User</h6>
        <p>As a user, you agree to use the Service responsibly and ethically. You are responsible for the prompts you provide and the way you use the resulting generated images. We are not liable for any misuse of the content created on our platform.</p>

        <h2>5. Consent</h2>
        <p>By using our Service, you hereby consent to this disclaimer and agree to its terms.</p>

        <h2>6. Update</h2>
        <p>Should we update, amend or make any changes to this document, those changes will be prominently posted here.</p>
      </div>
    </>
  );
};

export default DisclaimerPage;